export interface Icell {
    service: string | null,
    cost: number | null,
    name: string | null,
    date_to_do: string | null,
    username: string,
    birth_data: string | null,
    user_id: number,
    birth_time: string | null,
    country: string | null,
    city: string | null, 
    done: boolean,
    id: number, 
    order_date: string,
    client_id: string,
}